# Generated by Django 5.0.2 on 2024-11-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro_id', models.CharField(max_length=200)),
                ('nombre_libro', models.CharField(max_length=200)),
                ('editorial_libro', models.CharField(max_length=200)),
                ('año_libro', models.CharField(max_length=200)),
                ('categoria_libro', models.CharField(max_length=200)),
            ],
        ),
    ]
